version: "3.3"
services:

  app:
    image: tagger-app-ktor-ktor:0.0.1-SNAPSHOT
    container_name: tagger-app-ktor
    ports:
      - "8088:8088"
    expose:
      - "8088"
    environment:
      SQL_URL:     jdbc:postgresql://psql:5432/otus
      SQL_PASS:    pass
      SQL_USER:    postgres
      SQL_SCHEMA:  otus
      JWT_CERTURL: http://localhost:8081/auth/realms/otus/protocol/openid-connect/certs
    depends_on:
      psql:
        condition: service_healthy

  psql:
    image: postgres
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER:     postgres
      POSTGRES_DB:       otus
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout:  5s
      retries:  5

  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      - ./keycloak:/tmp
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    environment:
      KEYCLOAK_USER:     root
      KEYCLOAK_PASSWORD: toor
      KEYCLOAK_IMPORT:   "/tmp/realm-export.json"

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=root
      - opensearch_pass=toor
    volumes:
      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  keycloak_data:
  opensearch-data:
