### Create
POST http://127.0.0.1:8088/v1/obj/create
Content-Type: application/json

{
  "requestType": "objCreate",
  "requestId": "123456",
  "obj": {
    "name": "зАПИСКА",
    "content": "Входящая служебная записка",
    "objType": "text"
  },
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### Get unexisted ID
POST http://127.0.0.1:8088/v1/obj/read
Content-Type: application/json

{
  "requestType": "objRead",
  "requestId": "12345",
  "obj": {
    "id": "99999"
  },
  "debug": {
    "stub": "badId"
  }
}

### Read With Existed id
POST http://127.0.0.1:8088/v1/obj/read
Content-Type: application/json

{
  "requestType": "objRead",
  "requestId": "12345",
  "obj": {
    "id": "existed"
  },
  "debug": {
    "stub": "success"
  }
}

### Update
POST http://localhost:8088/v1/obj/update
Content-Type: application/json

{
  "requestType": "objUpdate",
  "requestId": "666",
  "obj": {
    "objType": "href",
    "id": "updated"
  },
  "debug": {
    "stub": "success"
  }
}

### Update with unexistedId
POST http://localhost:8088/v1/obj/update
Content-Type: application/json

{
  "requestType": "objUpdate",
  "requestId": "666",
  "obj": {
    "id": "668"
  },
  "debug": {
    "stub": "badId"
  }
}

### Delete existed
POST http://localhost:8088/v1/obj/delete
Content-Type: application/json

{
  "requestType": "objDelete",
  "requestId": "deleteId",
  "obj": {
    "id": "existed_id"
  },
  "debug": {
    "stub": "success"
  }
}

### Delete non-existed
POST http://localhost:8088/v1/obj/delete
Content-Type: application/json

{
  "requestType": "objDelete",
  "requestId": "deleteId_unknown",
  "obj": {
    "id": "unknownId"
  },
  "debug": {
    "stub": "badId"
  }
}

### Search by string
POST http://localhost:8088/v1/obj/search
Content-Type: application/json

{
  "requestType": "objSearch",
  "requestId": "search_1",
  "objFilter": {
    "searchString": "болт"
  },
  "debug": {
    "stub": "success"
  }
}

### Search by string with error
POST http://localhost:8088/v1/obj/search
Content-Type: application/json

{
  "requestType": "objSearch",
  "requestId": "search_1",
  "objFilter": {
    "searchString": "кто тут"
  },
  "debug": {
    "stub": "badSearchString"
  }
}




### Create obj 1
POST http://127.0.0.1:8088/v1/obj/create
Content-Type: application/json

{
  "requestId": "10",
  "obj": {
    "name": "Тест 1",
    "content": "Описание 1",
    "objType": "text"
  }
}

### Search obj 1
POST http://localhost:8088/v1/obj/search
Content-Type: application/json

{
  "requestId": "20",
  "objFilter": {
    "searchString": "Описание 1"
  }
}


### get all objs
POST http://localhost:8088/v1/obj/search
Content-Type: application/json

{
  "requestId": "30",
  "objFilter": {
    "searchString": ""
  }
}

### set tags for obj
POST http://127.0.0.1:8088/v1/obj/setTags
Content-Type: application/json

{
  "requestId": "40",
  "obj": {
    "id": "36b58040-23c3-424f-a442-0b3a7414e527",
    "lock": "d152845c-2697-4ae5-bea4-039a092c2058",
    "tags": [
      "tag1", "tag2", "tag3"
    ]
  }
}
